### ISSUE TITLE
Previous years Schedule is broken

### ISSUE THREAD

**Issue by ajpinedam** [pycascades/pycascades-cms#75]
When using the "Schedule" tab from previous years (2023 for example) is not returning any information and when inspecting the console we see a couple of errors.

![image](https://github.com/pycascades/pycascades-cms/assets/1900897/3b872bc6-c46b-45c3-84df-d7b64fc6d05b)

**Comment by bengerman13** [comment]
this is good to know, but IIRC deploying previous years' sites is really tricky, so I don't know how likely we are to fix it for the 2023 site (although we should obviously make sure it doesn't happen for 2024).
@AetherUnbound LMK if I'm misremembering that 😅 

This might be a hint that we should rethink our deployment strategy so that we can redeploy previous years' sites without trouble 🤔

**Comment by bengerman13** [comment]
Turns out this was because we marked 2023's schedule as private in pretalx 🤦🏻  - it's fixed now
